// src/app/shop/infrastructure/ng-components/item-detail/item-detail.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Item } from '../../../domain/item.model';

@Component({
    selector: 'app-item-detail',
    templateUrl: './item-detail.component.html',
    styleUrls: ['./item-detail.component.scss'],
    standalone: false
})
export class ItemDetailComponent implements OnInit {

   @Input() item: Item;

   constructor() { }

   ngOnInit(): void {
   }

}

// src/app/shop/infrastructure/ng-components/item-detail/ItemDetailComponent.tsx
import React, { useEffect } from 'react';
import { Item } from '../../../domain/item.model';

interface ItemDetailComponentProps {
  item: Item;
}

export const ItemDetailComponent: React.FC<ItemDetailComponentProps> = ({ item }) => {
  // Equivalent of ngOnInit — empty in the original Angular component
  useEffect(() => {
    // no-op, matching Angular's empty ngOnInit
  }, []);

  return (
    <p>item-detail works!</p>
  );
};
